import numpy as np

LOG_LEVEL = "DEBUG"

TEST_MODE = True
MANUAL_OVERRIDING_MODE = False
Z_FREEZE = True

LIDAR_NAME = "LidarSensor1"
CAMERA_NAME = "FrontCamera"

START_POS = [0, 0, 5, 3]
TARGET_POS = np.array([26.956, 1.0067, 3.1169])
 

SAFE_BOUND = 300
SAFE_BOUND_CENTER = np.array([0.0, 0.0, -1.0])

MAX_STEPS_IN_EPISODE_TRAIN = 30
MAX_STEPS_IN_EPISODE_TEST = 30

OBSERVATION_SPACE_LOW_LIDAR = -100
OBSERVATION_SPACE_HIGH_LIDAR = 100
OBSERVATION_SPACE_LOW_CAMERA = 0
OBSERVATION_SPACE_HIGH_CAMERA = 255

NUM_OF_POINTS = 2048
DIM_OF_POINTS = 3

CAMERA_HEIGHT = 480
CAMERA_WIDTH = 640
CAMERA_CHANNELS = 4

LIDAR_MAX_RANGE = 12
LIDAR_ANGLE = 10
LIDAR_ANGLE_TOLERANCE = 0.5

ACTION_SPACE_LOW = np.array([-10, -10, -10, -10])
ACTION_SPACE_HIGH = np.array([10, 10, 10, 10])
YAW_COEFFICIENT = 3

IMAGE_COMPRESSION = True

ACTION_DURATION = 1

GOAL_TOLERANCE = 3

TEST_MAX_EPISODES = 5
TEST_EPISODE_STEPS = 100

LIDAR_OBSTACLE_THRESHOLD = 3.0