REWARD_DEFAULT = -0.1

REWARD_DISTANCE_GAIN = 0.2
REWARD_DISTANCE_LOSS = -0.2

REWARD_OUT_OF_BOUNDS = -10
REWARD_MAX_STEPS_EXCEED = -50
REWARD_COLLISION = -150
REWARD_GOAL = 100

YOLO_DETECTED = 10
YOLO_NOT_DETECTED = -5
YOLO_AREA_COEFFICIENT = 200
YOLO_CENTER_OFFSET_COEFFICIENT = 10

VY_COEFFICIENT = -1.2
LIDAR_OBSTACLE_PENALTY = -5.0